apiVersion: aiops.prophet.io/v1alpha1
kind: HealthCheck
metadata:
  name: demo-app-health-check
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo-app
    namespace: default
  probes:
  - name: http-readiness
    type: http
    httpGet:
      path: /
      port: 80
      scheme: HTTP
  failureThreshold: 3
  periodSeconds: 10
  initialDelaySeconds: 5
  timeoutSeconds: 5
  remediation:
    action: restart
    cooldownSeconds: 300
    requireApproval: false