//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOViolation) DeepCopyInto(out *SLOViolation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOViolation.
func (in *SLOViolation) DeepCopy() *SLOViolation {
	if in == nil {
		return nil
	}
	out := new(SLOViolation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SLOViolation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOViolationList) DeepCopyInto(out *SLOViolationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SLOViolation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOViolationList.
func (in *SLOViolationList) DeepCopy() *SLOViolationList {
	if in == nil {
		return nil
	}
	out := new(SLOViolationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SLOViolationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOViolationSpec) DeepCopyInto(out *SLOViolationSpec) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]SLOAction, len(*in))
		copy(*out, *in)
	}
	out.HPARef = in.HPARef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOViolationSpec.
func (in *SLOViolationSpec) DeepCopy() *SLOViolationSpec {
	if in == nil {
		return nil
	}
	out := new(SLOViolationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOViolationStatus) DeepCopyInto(out *SLOViolationStatus) {
	*out = *in
	if in.LastViolated != nil {
		in, out := &in.LastViolated, &out.LastViolated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOViolationStatus.
func (in *SLOViolationStatus) DeepCopy() *SLOViolationStatus {
	if in == nil {
		return nil
	}
	out := new(SLOViolationStatus)
	in.DeepCopyInto(out)
	return out
}
