apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-slo-forecasting
  namespace: monitoring
data:
  slo-forecasts.yaml: |
    # SLO Error Budget Forecasting
    # Predicts when error budgets will be exhausted based on current burn rate
    slo_forecasts:
      # Availability SLO (99.9% uptime)
      availability_slo:
        slo_target: 0.999
        window: 30d
        query: |
          sum(rate(http_requests_total{status!~"5.."}[5m])) 
          / 
          sum(rate(http_requests_total[5m]))
        forecast_method: "prophet"
        forecast_horizon: 7d
        burn_rate_threshold: 0.1  # Alert if burn rate > 10% of budget
        alert_on_exhaustion_risk: true
        exhaustion_risk_days: 3  # Alert if forecasted exhaustion < 3 days
      
      # Latency SLO (p99 < 500ms)
      latency_slo:
        slo_target: 0.95  # 95% of requests < 500ms
        window: 30d
        query: |
          histogram_quantile(0.99, 
            sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service)
          ) < 0.5
        forecast_method: "prophet"
        forecast_horizon: 7d
        burn_rate_threshold: 0.15
        alert_on_exhaustion_risk: true
        exhaustion_risk_days: 5
      
      # Karpenter Node Availability SLO
      node_availability_slo:
        slo_target: 0.99  # 99% of pods scheduled within 2 minutes
        window: 30d
        query: |
          sum(rate(karpenter_nodes_ready_total[5m])) 
          / 
          sum(rate(karpenter_nodes_created_total[5m]))
        forecast_method: "prophet"
        forecast_horizon: 7d
        burn_rate_threshold: 0.2
        alert_on_exhaustion_risk: true
        exhaustion_risk_days: 7

