apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  limits:
    cpu: 500
    memory: 500Gi
  template:
    spec:
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - Standard_D2s_v3
            - Standard_B2s
            - Standard_B4ms
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]

