//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScale) DeepCopyInto(out *PredictiveScale) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScale.
func (in *PredictiveScale) DeepCopy() *PredictiveScale {
	if in == nil {
		return nil
	}
	out := new(PredictiveScale)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PredictiveScale) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScaleList) DeepCopyInto(out *PredictiveScaleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PredictiveScale, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScaleList.
func (in *PredictiveScaleList) DeepCopy() *PredictiveScaleList {
	if in == nil {
		return nil
	}
	out := new(PredictiveScaleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PredictiveScaleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScaleSpec) DeepCopyInto(out *PredictiveScaleSpec) {
	*out = *in
	out.NodePoolRef = in.NodePoolRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScaleSpec.
func (in *PredictiveScaleSpec) DeepCopy() *PredictiveScaleSpec {
	if in == nil {
		return nil
	}
	out := new(PredictiveScaleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScaleStatus) DeepCopyInto(out *PredictiveScaleStatus) {
	*out = *in
	if in.LastScaled != nil {
		in, out := &in.LastScaled, &out.LastScaled
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScaleStatus.
func (in *PredictiveScaleStatus) DeepCopy() *PredictiveScaleStatus {
	if in == nil {
		return nil
	}
	out := new(PredictiveScaleStatus)
	in.DeepCopyInto(out)
	return out
}
