//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeySelector) DeepCopyInto(out *ConfigMapKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeySelector.
func (in *ConfigMapKeySelector) DeepCopy() *ConfigMapKeySelector {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticChecks) DeepCopyInto(out *DiagnosticChecks) {
	*out = *in
	if in.ServiceDependencies != nil {
		in, out := &in.ServiceDependencies, &out.ServiceDependencies
		*out = make([]ServiceDependency, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticChecks.
func (in *DiagnosticChecks) DeepCopy() *DiagnosticChecks {
	if in == nil {
		return nil
	}
	out := new(DiagnosticChecks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticIssue) DeepCopyInto(out *DiagnosticIssue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticIssue.
func (in *DiagnosticIssue) DeepCopy() *DiagnosticIssue {
	if in == nil {
		return nil
	}
	out := new(DiagnosticIssue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticRemediation) DeepCopyInto(out *DiagnosticRemediation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticRemediation.
func (in *DiagnosticRemediation) DeepCopy() *DiagnosticRemediation {
	if in == nil {
		return nil
	}
	out := new(DiagnosticRemediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosticRemediation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticRemediationList) DeepCopyInto(out *DiagnosticRemediationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiagnosticRemediation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticRemediationList.
func (in *DiagnosticRemediationList) DeepCopy() *DiagnosticRemediationList {
	if in == nil {
		return nil
	}
	out := new(DiagnosticRemediationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosticRemediationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticRemediationSpec) DeepCopyInto(out *DiagnosticRemediationSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	in.Diagnostics.DeepCopyInto(&out.Diagnostics)
	in.Remediation.DeepCopyInto(&out.Remediation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticRemediationSpec.
func (in *DiagnosticRemediationSpec) DeepCopy() *DiagnosticRemediationSpec {
	if in == nil {
		return nil
	}
	out := new(DiagnosticRemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosticRemediationStatus) DeepCopyInto(out *DiagnosticRemediationStatus) {
	*out = *in
	if in.LastDiagnosed != nil {
		in, out := &in.LastDiagnosed, &out.LastDiagnosed
		*out = (*in).DeepCopy()
	}
	if in.LastRemediated != nil {
		in, out := &in.LastRemediated, &out.LastRemediated
		*out = (*in).DeepCopy()
	}
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = make([]DiagnosticIssue, len(*in))
		copy(*out, *in)
	}
	if in.Remediations != nil {
		in, out := &in.Remediations, &out.Remediations
		*out = make([]RemediationAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosticRemediationStatus.
func (in *DiagnosticRemediationStatus) DeepCopy() *DiagnosticRemediationStatus {
	if in == nil {
		return nil
	}
	out := new(DiagnosticRemediationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVarSource) DeepCopyInto(out *EnvVarSource) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(ConfigMapKeySelector)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVarSource.
func (in *EnvVarSource) DeepCopy() *EnvVarSource {
	if in == nil {
		return nil
	}
	out := new(EnvVarSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVarSpec) DeepCopyInto(out *EnvVarSpec) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(EnvVarSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVarSpec.
func (in *EnvVarSpec) DeepCopy() *EnvVarSpec {
	if in == nil {
		return nil
	}
	out := new(EnvVarSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationAction) DeepCopyInto(out *RemediationAction) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationAction.
func (in *RemediationAction) DeepCopy() *RemediationAction {
	if in == nil {
		return nil
	}
	out := new(RemediationAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationActions) DeepCopyInto(out *RemediationActions) {
	*out = *in
	out.DefaultResources = in.DefaultResources
	if in.RequiredEnvVars != nil {
		in, out := &in.RequiredEnvVars, &out.RequiredEnvVars
		*out = make([]EnvVarSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationActions.
func (in *RemediationActions) DeepCopy() *RemediationActions {
	if in == nil {
		return nil
	}
	out := new(RemediationActions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSpec.
func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceDependency) DeepCopyInto(out *ServiceDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceDependency.
func (in *ServiceDependency) DeepCopy() *ServiceDependency {
	if in == nil {
		return nil
	}
	out := new(ServiceDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSpec) DeepCopyInto(out *TargetSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSpec.
func (in *TargetSpec) DeepCopy() *TargetSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSpec)
	in.DeepCopyInto(out)
	return out
}
