apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress-nginx
  valuesContent: |-
    controller:
      replicaCount: 2
      service:
        type: LoadBalancer
        annotations:
          cloud.google.com/load-balancer-type: "External"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

