apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
---
# Cluster API Core Components
# Note: Install via clusterctl or Helm in production
# clusterctl init --infrastructure aws,gcp,azure

apiVersion: v1
kind: ServiceAccount
metadata:
  name: capi-controller-manager
  namespace: capi-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-controller-manager
  namespace: capi-system
  labels:
    cluster.x-k8s.io/provider: cluster-api
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: cluster-api
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: cluster-api
    spec:
      serviceAccountName: capi-controller-manager
      containers:
      - name: manager
        image: gcr.io/k8s-staging-cluster-api/cluster-api-controller:latest
        command:
        - /manager
        args:
        - --metrics-bind-addr=:8080
        - --feature-gates=MachinePool=true,ClusterResourceSet=true
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
# Cluster API CRDs are installed separately via clusterctl
# This manifest is a placeholder for the management cluster setup

