apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/part-of: prophet
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/part-of: prophet
---
# RBAC for Headlamp: auth flow + read-only access to resources.
# Headlamp will still respect *end-user* Kubernetes RBAC (users authenticate with their own token/OIDC).
# This ServiceAccount needs read access to proxy/display resources that the user's token allows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/part-of: prophet
rules:
  # Auth/authorization checks
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
  # Read-only access to resources (Headlamp proxies requests using user's token, but needs to list/discover)
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  # Prophet CRDs
  - apiGroups: ["aiops.prophet.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/part-of: prophet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: headlamp
subjects:
  - kind: ServiceAccount
    name: headlamp
    namespace: headlamp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/part-of: prophet
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: headlamp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headlamp
        app.kubernetes.io/part-of: prophet
    spec:
      serviceAccountName: headlamp
      containers:
        - name: headlamp
          # Pin this to a specific tag in production.
          image: ghcr.io/headlamp-k8s/headlamp:latest
          imagePullPolicy: IfNotPresent
          command:
            - /headlamp/headlamp-server
          args:
            - -html-static-dir
            - /headlamp/frontend
            - -plugins-dir
            - /headlamp/plugins
            - -in-cluster
            - -watch-plugins-changes=true
          ports:
            - name: http
              containerPort: 4466
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: headlamp-plugin-prophet
              mountPath: /headlamp/plugins/prophet
              readOnly: true
            - name: headlamp-plugin-grafana
              mountPath: /headlamp/plugins/grafana
              readOnly: true
      volumes:
        - name: headlamp-plugin-prophet
          configMap:
            name: headlamp-plugin-prophet
        - name: headlamp-plugin-grafana
          configMap:
            name: headlamp-plugin-grafana
---
apiVersion: v1
kind: Service
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/part-of: prophet
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: headlamp
  ports:
    - name: http
      port: 80
      targetPort: http


