apiVersion: v1
kind: ConfigMap
metadata:
  name: headlamp-plugin-test
  namespace: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/part-of: prophet
data:
  package.json: |
    {
      "name": "test",
      "version": "0.1.0",
      "description": "Minimal test plugin",
      "main": "main.js"
    }
  main.js: |
    (function() {
      'use strict';
      if (typeof pluginLib === 'undefined') {
        return;
      }
      var lib = pluginLib;
      var React = lib.React;
      
      function TestPage() {
        return React.createElement('div', { style: { padding: 16 } },
          React.createElement('h1', null, 'Test Plugin Works!')
        );
      }
      
      if (lib.registerRoute) {
        lib.registerRoute({
          path: '/test',
          exact: true,
          component: TestPage
        });
      }
      
      if (lib.registerSidebarItem) {
        lib.registerSidebarItem({
          parent: null,
          name: 'test',
          label: 'Test',
          url: '/test',
          icon: 'mdi:test-tube'
        });
      }
    })();

