apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  limits:
    cpu: 500
    memory: 500Gi
  template:
    spec:
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - e2-medium
            - e2-standard-2
            - n1-standard-2
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]

