apiVersion: v1
kind: Namespace
metadata:
  name: k8sgpt
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sgpt-operator
  namespace: k8sgpt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sgpt-operator
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["karpenter.sh"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sgpt-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8sgpt-operator
subjects:
  - kind: ServiceAccount
    name: k8sgpt-operator
    namespace: k8sgpt
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8sgpt-config
  namespace: k8sgpt
data:
  config.yaml: |
    # K8sGPT Configuration
    # AI-powered Kubernetes diagnostics and analysis
    defaultProvider: openai  # or "azureopenai", "localai", "anthropic"
    model: gpt-4o-mini  # or "gpt-4", "claude-3-haiku", etc.
    
    # Analysis settings
    filters:
      - ResourceQuota
      - Pod
      - Node
      - Deployment
      - Service
      - Ingress
      - PersistentVolumeClaim
      - NetworkPolicy
      - KarpenterNodePool
      - KarpenterNodeClass
    
    # Severity levels
    severity:
      critical: true
      warning: true
      info: false
    
    # Auto-analysis triggers
    triggers:
      - event: "PodCrashLoopBackOff"
        analyze: true
        explain: true
        suggest_fix: true
      - event: "NodeNotReady"
        analyze: true
        explain: true
        suggest_fix: true
      - event: "KarpenterNodeProvisioningFailed"
        analyze: true
        explain: true
        suggest_fix: true
      - alert: "HighCPUUsage"
        analyze: true
        explain: true
        suggest_fix: true
    
    # Integration with Prometheus alerts
    prometheus:
      enabled: true
      endpoint: "http://prometheus.monitoring.svc.cluster.local:9090"
      alert_rules:
        - name: ".*"
          severity: "critical"
          auto_analyze: true
    
    # Output format
    output:
      format: "json"  # or "yaml", "table"
      include_explanation: true
      include_suggestions: true
      include_commands: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sgpt-operator
  namespace: k8sgpt
  labels:
    app: k8sgpt-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sgpt-operator
  template:
    metadata:
      labels:
        app: k8sgpt-operator
    spec:
      serviceAccountName: k8sgpt-operator
      containers:
        - name: k8sgpt
          image: k8sgpt/k8sgpt:latest
          args:
            - server
            - --config=/etc/k8sgpt/config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/k8sgpt
          env:
            - name: K8SGPT_PROVIDER
              value: "openai"
            - name: K8SGPT_MODEL
              value: "gpt-4o-mini"
            # Add your API key via Secret
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: k8sgpt-secrets
                  key: openai-api-key
                  optional: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: k8sgpt-config
---
apiVersion: v1
kind: Service
metadata:
  name: k8sgpt-operator
  namespace: k8sgpt
  labels:
    app: k8sgpt-operator
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: k8sgpt-operator
---
# K8sGPT Analysis CRD (example - adjust based on actual K8sGPT operator)
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: k8sgptanalyses.aiops.k8s.io
spec:
  group: aiops.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                resourceType:
                  type: string
                namespace:
                  type: string
                filters:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                issues:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      severity:
                        type: string
                      explanation:
                        type: string
                      suggestion:
                        type: string
  scope: Namespaced
  names:
    plural: k8sgptanalyses
    singular: k8sgptanalysis
    kind: K8sGPTAnalysis
---
# Example: Trigger K8sGPT analysis on alert
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8sgpt-webhook
  namespace: k8sgpt
data:
  webhook-config.yaml: |
    # Webhook configuration for Prometheus Alertmanager
    # Triggers K8sGPT analysis when alerts fire
    receivers:
      - name: k8sgpt-analyzer
        webhook_configs:
          - url: "http://k8sgpt-operator.k8sgpt.svc.cluster.local:8080/api/v1/analyze"
            http_config:
              bearer_token_file: /var/run/secrets/k8sgpt/token
            send_resolved: false

