//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsOnExceedSpec) DeepCopyInto(out *ActionsOnExceedSpec) {
	*out = *in
	in.Notify.DeepCopyInto(&out.Notify)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsOnExceedSpec.
func (in *ActionsOnExceedSpec) DeepCopy() *ActionsOnExceedSpec {
	if in == nil {
		return nil
	}
	out := new(ActionsOnExceedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetGuard) DeepCopyInto(out *BudgetGuard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetGuard.
func (in *BudgetGuard) DeepCopy() *BudgetGuard {
	if in == nil {
		return nil
	}
	out := new(BudgetGuard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BudgetGuard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetGuardList) DeepCopyInto(out *BudgetGuardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BudgetGuard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetGuardList.
func (in *BudgetGuardList) DeepCopy() *BudgetGuardList {
	if in == nil {
		return nil
	}
	out := new(BudgetGuardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BudgetGuardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetGuardSpec) DeepCopyInto(out *BudgetGuardSpec) {
	*out = *in
	out.Budget = in.Budget
	in.ActionsOnExceed.DeepCopyInto(&out.ActionsOnExceed)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetGuardSpec.
func (in *BudgetGuardSpec) DeepCopy() *BudgetGuardSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetGuardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetGuardStatus) DeepCopyInto(out *BudgetGuardStatus) {
	*out = *in
	if in.ProjectedExceedTime != nil {
		in, out := &in.ProjectedExceedTime, &out.ProjectedExceedTime
		*out = (*in).DeepCopy()
	}
	if in.LastRefreshTime != nil {
		in, out := &in.LastRefreshTime, &out.LastRefreshTime
		*out = (*in).DeepCopy()
	}
	if in.ActionsTaken != nil {
		in, out := &in.ActionsTaken, &out.ActionsTaken
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetGuardStatus.
func (in *BudgetGuardStatus) DeepCopy() *BudgetGuardStatus {
	if in == nil {
		return nil
	}
	out := new(BudgetGuardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetLimit) DeepCopyInto(out *BudgetLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetLimit.
func (in *BudgetLimit) DeepCopy() *BudgetLimit {
	if in == nil {
		return nil
	}
	out := new(BudgetLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotifySpec) DeepCopyInto(out *NotifySpec) {
	*out = *in
	if in.EmailRecipients != nil {
		in, out := &in.EmailRecipients, &out.EmailRecipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotifySpec.
func (in *NotifySpec) DeepCopy() *NotifySpec {
	if in == nil {
		return nil
	}
	out := new(NotifySpec)
	in.DeepCopyInto(out)
	return out
}
