apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: default
  labels:
    app: backend-api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
        tier: backend
    spec:
      containers:
      - name: backend
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: backend-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        readinessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: backend-config
        configMap:
          name: backend-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location /api/health {
            return 200 '{"status": "healthy", "service": "backend-api"}';
            add_header Content-Type application/json;
        }

        location /api/users {
            return 200 '{"users": [{"id": 1, "name": "John"}, {"id": 2, "name": "Jane"}]}';
            add_header Content-Type application/json;
        }

        location / {
            return 404 '{"error": "Not Found"}';
            add_header Content-Type application/json;
        }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    app: backend-api
    tier: backend
spec:
  selector:
    app: backend-api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP