apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  limits:
    cpu: 2000
    memory: 2000Gi
  template:
    spec:
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - t3.large
            - t3.xlarge
            - m5.large
            - m5.xlarge
            - m5.2xlarge
            - m5.4xlarge
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]  # Mix for production
      taints: []  # No taints for general workloads
  disruption:
    consolidationPolicy: WhenUnderutilized
    consolidateAfter: 5m
    expireAfter: 720h

