apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  limits:
    cpu: 2000
    memory: 2000Gi
  template:
    spec:
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - Standard_D2s_v3
            - Standard_D4s_v3
            - Standard_D8s_v3
            - Standard_D16s_v3
            - Standard_B4ms
            - Standard_B8ms
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["regular", "spot"]
  disruption:
    consolidationPolicy: WhenUnderutilized
    consolidateAfter: 5m
    expireAfter: 720h

