apiVersion: v1
kind: Pod
metadata:
  name: test-app-2
  labels:
    app.kubernetes.io/name: my-app  # This matches the LabelEnforcer selector
    app.kubernetes.io/component: test
spec:
  containers:
  - name: nginx
    image: nginx:1.21-alpine
    ports:
    - containerPort: 80
  restartPolicy: Never