apiVersion: v1
kind: Pod
metadata:
  name: test-app
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/version: v1.0.0
spec:
  containers:
  - name: nginx
    image: nginx:1.21-alpine
    ports:
    - containerPort: 80
  restartPolicy: Never