# golangci-lint configuration for Prophet operators
# Run with: golangci-lint run ./...

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocritic
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - gocyclo
    - dupl
    - gosec
    - gocognit
  disable:
    - lll
    - typecheck  # Disabled due to module cache issues - enabled via CLI flag instead
    - exportloopref  # Deprecated, replaced by copyloopvar

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
        - gosec
        - dupl
  max-issues-per-linter: 0
  max-same-issues: 0

