apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    secret:
      name: k8sgpt-secret
      key: OPENAI_API_KEY
  version: v0.4.26  # This pins to the latest K8sGPT core version