apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: autonomousactions.aiops.prophet.io
spec:
  group: aiops.prophet.io
  names:
    kind: AutonomousAction
    listKind: AutonomousActionList
    plural: autonomousactions
    singular: autonomousaction
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              trigger:
                type: object
              llm:
                type: object
              context:
                type: object
              approvalMode:
                type: string
              constraints:
                type: object
              mcpServer:
                type: string
          status:
            type: object
    subresources:
      status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autonomous-agent-controller-manager
  namespace: prophet-operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autonomous-agent-manager-role
rules:
- apiGroups:
  - aiops.prophet.io
  resources:
  - autonomousactions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - aiops.prophet.io
  resources:
  - autonomousactions/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - get
  - list
  - watch
  - delete
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autonomous-agent-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autonomous-agent-manager-role
subjects:
- kind: ServiceAccount
  name: autonomous-agent-controller-manager
  namespace: prophet-operators
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autonomous-agent-controller-manager
  namespace: prophet-operators
  labels:
    app: autonomous-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autonomous-agent
  template:
    metadata:
      labels:
        app: autonomous-agent
    spec:
      serviceAccountName: autonomous-agent-controller-manager
      containers:
      - name: manager
        image: ghcr.io/prophet-aiops/prophet-autonomous-agent:latest
        command:
        - /manager
        args:
        - --leader-elect
        - --mcp-port=8082
        - --mcp-tls-enabled=true
        - --mcp-tls-port=8443
        - --mcp-tls-cert-file=/etc/mcp/tls/tls.crt
        - --mcp-tls-key-file=/etc/mcp/tls/tls.key
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: mcp-tls
          mountPath: /etc/mcp/tls
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      - name: ollama
        image: ollama/ollama:latest
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
      volumes:
      - name: ollama-data
        emptyDir: {}
      - name: mcp-tls
        secret:
          # Expected: a `kubernetes.io/tls` Secret with keys `tls.crt` and `tls.key`.
          # Ensure the server cert includes the Service DNS name(s) in SANs, e.g.:
          # - autonomous-agent-mcp.prophet-operators.svc.cluster.local
          # - autonomous-agent-service.default.svc.cluster.local (if using the ExternalName alias in `clusters/common/aiops/mcp/client-config.yaml`)
          secretName: autonomous-agent-mcp-tls
---
apiVersion: v1
kind: Service
metadata:
  name: autonomous-agent-mcp
  namespace: prophet-operators
  labels:
    app: autonomous-agent
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 8443
    name: mcp-tls
  - port: 8082
    # Serve TLS on 8082 for clients that expect the MCP port to be 8082.
    # This forwards TCP to the MCP server's HTTPS listener (default :8443).
    targetPort: 8443
    name: mcp
  selector:
    app: autonomous-agent
---
# Example AutonomousAction resource
apiVersion: aiops.prophet.io/v1alpha1
kind: AutonomousAction
metadata:
  name: auto-remediate-errors
  namespace: default
spec:
  trigger:
    type: anomaly
    anomalyScoreThreshold: 0.8
  llm:
    provider: ollama
    model: phi-3
    endpoint: http://localhost:11434
    temperature: 0.7
    maxTokens: 1000
    systemPrompt: |
      You are an expert Kubernetes SRE. Analyze cluster anomalies and propose safe remediation actions.
      Consider: impact, safety, and best practices. Return JSON with reasoning and proposed action.
  context:
    includeK8sGPT: true
    includeMetrics: true
    includeEvents: true
    includeHubble: true
    timeWindow: 5m
    namespaces:
    - default
  approvalMode: autonomous
  constraints:
    allowedActions:
    - restart
    - scale
    - rollback
    forbiddenNamespaces:
    - kube-system
    maxConcurrent: 3
    cooldownSeconds: 300

