apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        workload-type: general
    spec:
      nodeClassRef:
        apiVersion: karpenter.azure.com/v1alpha2
        kind: AKSNodeClass
        name: default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - Standard_D2s_v3
            - Standard_D4s_v3
            - Standard_D8s_v3
            - Standard_B2s
            - Standard_B4ms
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["regular", "spot"]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    expireAfter: 720h
  limits:
    cpu: 1000
    memory: 1000Gi
  weight: 10

